### ISSUE TITLE
Server Banner Changing Automation

### ISSUE THREAD

**Issue by defaultyeah** [TheDarkun/DarkBot#24]
Add a feature that allows people to upload their own server banners to the bot, which would then automatically rotate the server banners at set intervals. Could be animated/static or both.

**Comment by TheDarkun** [comment]
# Automatic Banner Rotation
This message is the full feature-set and will be split into multiple issues. Thanks to a yearly Nitro boost, we have the ability to add banners on our server.
## Problem
- It would be great if everyone could have the option to add their own image/gif as a banner
  - Ideally, users should not be limited by others
- Attention spans are too low nowadays, and it's necessary to change the banner frequently
  - People are lazy, so automating everything would be best
## Solution
1. Everyone will have the option to submit **3** custom banners
2. The banner will change every day at **20:00**
3. Users will be able to change/delete their own banners both through Discord and the website
### Discord-End
**/add-banner [option:image]**
- adds a banner if the limit isn't exceeded

**/show-banners**
- displays all custom banners and their IDs

**/delete-banner [option:id]**
- removes a banner based on its ID

**/update-banner [option:image] [option:id]**
- replaces the old banner with a new one based on its ID

### Front-End
- a new page will be added
- it will display all users who have at least 1 custom banner
  - clicking on a user will display all their banners
    - they can be removed or replaced
